user = User.create(username: "lilian", password: "lilo", age: 25)
user = User.create(username: "lazarus", password: "mary", age: 25)
user = User.create(username: "pablo", password: "lobpa", age: 25)
user = User.create(username: "gustavo", password: "stavo", age: 25)
user = User.create(username: "gringo", password: "grin", age: 25)
